### ISSUE TITLE
Segmentation fault when trying to build pion/webrtc for WebAssembly

### ISSUE THREAD

**Issue by ungive** [tinygo-org/tinygo#2067]
Hello there,

I am trying to build [pion/webrtc](https://github.com/pion/webrtc) with TinyGo in order to write WebRTC code once in Go and compile it for the web with WebAssembly by leveraging the native Browser API (Pion uses `syscall/js` to do that).

In order to do that some work was necessary to fix various compiler errors about undefined methods, unavailable packages, etc. I've forked the necessary repositories and made those changes until I got a segmentation fault. At this point I'm not really sure how to continue as the error message does not seem to contain any useful information (to my eye). I was hoping someone could help or give me some insight.

I've made a repository with a minimum working example: https://github.com/vonas/webrtc-tinygo-wasm

Notice the `deps` folder with submodules of all the forked repositories to which I have made changes and the corresponding `replace` directives in the `go.mod` file.

I am trying to compile `webrtc/data-channels/jsfiddle/main.go` [which is taken from the original webrtc repository](https://github.com/pion/webrtc/blob/e3ced781d0e5631ff8c54c38d4ff4d79aee7fb39/examples/data-channels/jsfiddle/main.go). It's an example to create a DataChannel between a CLI program and the browser. The mentioned `main.go` file contains the code that should be compiled to WebAssembly.

To compile run `make` in the root of my repository.

When compiling I get the following error:

```
(go1.16.7) mustang:webrtc-tinygo-wasm jonas% make 
tinygo build -o webrtc/data-channels/jsfiddle/demo.wasm -target wasm webrtc/data-channels/jsfiddle/main.go
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x416b0a8]

runtime stack:
runtime.throw(0x45991da, 0x2a)
        /usr/local/go/src/runtime/panic.go:1116 +0x72
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:701 +0x46a

goroutine 15 [syscall]:
runtime.cgocall(0xe44630, 0xc0040b1bd8, 0xe45f60)
        /usr/local/go/src/runtime/cgocall.go:133 +0x5b fp=0xc0040b1ba8 sp=0xc0040b1b70 pc=0xa6af5b
tinygo.org/x/go-llvm._Cfunc_LLVMConstExtractValue(0x0, 0xc00867b858, 0x1, 0x0)
        _cgo_gotypes.go:3051 +0x4e fp=0xc0040b1bd8 sp=0xc0040b1ba8 pc=0xd08b6e
tinygo.org/x/go-llvm.ConstExtractValue.func1(0x0, 0xc00867b858, 0x1, 0xc00867b858)
        /go/pkg/mod/tinygo.org/x/go-llvm@v0.0.0-20210325115028-e7b85195e81c/ir.go:1010 +0x60 fp=0xc0040b1c08 sp=0xc0040b1bd8 pc=0xd30f50
tinygo.org/x/go-llvm.ConstExtractValue(0x0, 0xc00867b858, 0x1, 0x1, 0x0)
        /go/pkg/mod/tinygo.org/x/go-llvm@v0.0.0-20210325115028-e7b85195e81c/ir.go:1010 +0x44 fp=0xc0040b1c38 sp=0xc0040b1c08 pc=0xd1d274
github.com/tinygo-org/tinygo/interp.(*runner).run(0xc000120090, 0xc003e538b0, 0xc00873bf10, 0x8, 0xf, 0xc005041ec0, 0xc0086dd3a0, 0x18, 0x0, 0xc0040b2750, ...)
        /home/circleci/project/interp/interpreter.go:442 +0x6eab fp=0xc0040b2648 sp=0xc0040b1c38 pc=0xdc6cdb
github.com/tinygo-org/tinygo/interp.(*runner).run(0xc000120090, 0xc003e53860, 0xc0086b8310, 0x7, 0x7, 0xc0050b3890, 0xc0086dcf40, 0x14, 0x0, 0xc008672800, ...)
        /home/circleci/project/interp/interpreter.go:482 +0x6541 fp=0xc0040b3058 sp=0xc0040b2648 pc=0xdc6371
github.com/tinygo-org/tinygo/interp.(*runner).run(0xc000120090, 0xc003e53770, 0xc00856c310, 0x8, 0xf, 0xc0053e9ad0, 0xc00867a1f0, 0x10, 0x0, 0xb137d80, ...)
        /home/circleci/project/interp/interpreter.go:482 +0x6541 fp=0xc0040b3a68 sp=0xc0040b3058 pc=0xdc6371
github.com/tinygo-org/tinygo/interp.(*runner).run(0xc000120090, 0xc003e53720, 0xc0051130d0, 0x2, 0x3, 0xc0053e93e0, 0xc00854d9e0, 0xc, 0x0, 0x7fd2750, ...)
        /home/circleci/project/interp/interpreter.go:482 +0x6541 fp=0xc0040b4478 sp=0xc0040b3a68 pc=0xdc6371
github.com/tinygo-org/tinygo/interp.(*runner).run(0xc000120090, 0xc003e536d0, 0xc005112990, 0x2, 0x3, 0xc0053e8990, 0xc00854d5f0, 0x8, 0x0, 0xa6c0f5, ...)
        /home/circleci/project/interp/interpreter.go:482 +0x6541 fp=0xc0040b4e88 sp=0xc0040b4478 pc=0xdc6371
github.com/tinygo-org/tinygo/interp.(*runner).run(0xc000120090, 0xc003e53680, 0x0, 0x0, 0x0, 0x0, 0x4584648, 0x4, 0x0, 0x0, ...)
        /home/circleci/project/interp/interpreter.go:482 +0x6541 fp=0xc0040b5898 sp=0xc0040b4e88 pc=0xdc6371
github.com/tinygo-org/tinygo/interp.Run(0x7d45b30, 0xc00005fd00, 0x0, 0x0)
        /home/circleci/project/interp/interp.go:112 +0x730 fp=0xc0040b5da0 sp=0xc0040b5898 pc=0xdbddf0
github.com/tinygo-org/tinygo/builder.optimizeProgram(0x7d45b30, 0xc0002ea150, 0xc0027d66c0, 0x2)
        /home/circleci/project/builder/build.go:679 +0x3f fp=0xc0040b5e10 sp=0xc0040b5da0 pc=0xe083cf
github.com/tinygo-org/tinygo/builder.Build.func2(0xc005d7a540, 0x0, 0x0)
        /home/circleci/project/builder/build.go:392 +0x812 fp=0xc0040b5f70 sp=0xc0040b5e10 pc=0xe190b2
github.com/tinygo-org/tinygo/builder.jobWorker(0xc003ed1920, 0xc003ed18c0)
        /home/circleci/project/builder/jobs.go:165 +0xe0 fp=0xc0040b5fd0 sp=0xc0040b5f70 pc=0xe11580
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc0040b5fd8 sp=0xc0040b5fd0 pc=0xaca751
created by github.com/tinygo-org/tinygo/builder.runJobs
        /home/circleci/project/builder/jobs.go:84 +0xc5

goroutine 1 [chan receive]:
github.com/tinygo-org/tinygo/builder.runJobs(0xc0089e1420, 0x3, 0x4, 0x0, 0x0)
        /home/circleci/project/builder/jobs.go:116 +0x12f
github.com/tinygo-org/tinygo/builder.Build(0x7ffd265a1683, 0x25, 0x7ffd265a164e, 0x27, 0xc0002ea150, 0xc000659ae0, 0x0, 0x0)
        /home/circleci/project/builder/build.go:620 +0x26c4
main.Build(0x7ffd265a1683, 0x25, 0x7ffd265a164e, 0x27, 0xc0000ae100, 0x0, 0x12)
        /home/circleci/project/main.go:131 +0xc5
main.main()
        /home/circleci/project/main.go:1132 +0x259a

goroutine 8 [chan receive]:
github.com/tinygo-org/tinygo/builder.jobWorker(0xc003ed1920, 0xc003ed18c0)
        /home/circleci/project/builder/jobs.go:162 +0x82
created by github.com/tinygo-org/tinygo/builder.runJobs
        /home/circleci/project/builder/jobs.go:84 +0xc5

goroutine 9 [chan receive]:
github.com/tinygo-org/tinygo/builder.jobWorker(0xc003ed1920, 0xc003ed18c0)
        /home/circleci/project/builder/jobs.go:162 +0x82
created by github.com/tinygo-org/tinygo/builder.runJobs
        /home/circleci/project/builder/jobs.go:84 +0xc5

goroutine 10 [chan receive]:
github.com/tinygo-org/tinygo/builder.jobWorker(0xc003ed1920, 0xc003ed18c0)
        /home/circleci/project/builder/jobs.go:162 +0x82
created by github.com/tinygo-org/tinygo/builder.runJobs
        /home/circleci/project/builder/jobs.go:84 +0xc5

goroutine 11 [chan receive]:
github.com/tinygo-org/tinygo/builder.jobWorker(0xc003ed1920, 0xc003ed18c0)
        /home/circleci/project/builder/jobs.go:162 +0x82
created by github.com/tinygo-org/tinygo/builder.runJobs
        /home/circleci/project/builder/jobs.go:84 +0xc5

goroutine 12 [chan receive]:
github.com/tinygo-org/tinygo/builder.jobWorker(0xc003ed1920, 0xc003ed18c0)
        /home/circleci/project/builder/jobs.go:162 +0x82
created by github.com/tinygo-org/tinygo/builder.runJobs
        /home/circleci/project/builder/jobs.go:84 +0xc5

goroutine 13 [chan receive]:
github.com/tinygo-org/tinygo/builder.jobWorker(0xc003ed1920, 0xc003ed18c0)
        /home/circleci/project/builder/jobs.go:162 +0x82
created by github.com/tinygo-org/tinygo/builder.runJobs
        /home/circleci/project/builder/jobs.go:84 +0xc5

goroutine 14 [chan receive]:
github.com/tinygo-org/tinygo/builder.jobWorker(0xc003ed1920, 0xc003ed18c0)
        /home/circleci/project/builder/jobs.go:162 +0x82
created by github.com/tinygo-org/tinygo/builder.runJobs
        /home/circleci/project/builder/jobs.go:84 +0xc5
make: *** [Makefile:7: build] Fehler 2
```

Here is information about my system, Go and TinyGo version:

```
(go1.16.7) mustang:webrtc-tinygo-wasm jonas% uname -r             
5.14.0-rc2-1-mainline-g7a519f4c0af5
(go1.16.7) mustang:webrtc-tinygo-wasm jonas% go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/jonas/.cache/go-build"
GOENV="/home/jonas/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/jonas/go1.16.7/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/jonas/go1.16.7"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/jonas/sdk/go1.16.7"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/jonas/sdk/go1.16.7/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.7"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/jonas/git/vonas/webrtc-tinygo-wasm/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build962043915=/tmp/go-build -gno-record-gcc-switches"
(go1.16.7) mustang:webrtc-tinygo-wasm jonas% tinygo env
GOOS="linux"
GOARCH="amd64"
GOROOT="/home/jonas/sdk/go1.16.7"
GOPATH="/home/jonas/go1.16.7"
GOCACHE="/home/jonas/.cache/tinygo"
CGO_ENABLED="1"
TINYGOROOT="/usr/lib/tinygo"
```

Thank you for reading. I hope someone's able to steer me in the right direction!

Cheers.

**Comment by ungive** [comment]
I've done a little more digging and found that the `CryptoUint64` function of the `pion/randutil` package is one possible source of this issue: https://github.com/pion/randutil/blob/3e7aefb6fd280d89fca72f1596348f1939525187/crypto.go#L24

I've pushed an example of that: https://github.com/vonas/webrtc-tinygo-wasm/commit/8c6b4f04178f46a59e4d5f6190c18a10dce6df4e

This is the relevant part that only compiles in odd circumstances:
```go
package main

import (
	"crypto/rand"
	"encoding/binary"
)

// Taken from "randutil.CryptoUint64" of pion/randutil.
func main() {
	var v uint64
	if err := binary.Read(rand.Reader, binary.LittleEndian, &v); err != nil {
		return
	}
	_ = v
}
```

I've added three commands to my `Makefile` that compile the above code in different ways with varying results:

```
(go1.16.7) mustang:webrtc-tinygo-wasm jonas% make minimal1
tinygo build -opt 0 -o minimal/main.wasm -target wasm ./minimal/main.go
panic: unexpected getFuncPtrCall

goroutine 16 [running]:
github.com/tinygo-org/tinygo/transform.LowerFuncValues(0x7f9dcc002aa0)
        /home/circleci/project/transform/func-lowering.go:196 +0x129a
github.com/tinygo-org/tinygo/transform.Optimize(0x7f9dcc002aa0, 0xc0002e2150, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/circleci/project/transform/optimizer.go:106 +0x1241
github.com/tinygo-org/tinygo/builder.optimizeProgram(0x7f9dcc002aa0, 0xc0002e2150, 0xc001260300, 0x2)
        /home/circleci/project/builder/build.go:721 +0x13d
github.com/tinygo-org/tinygo/builder.Build.func2(0xc003dcaea0, 0x0, 0x0)
        /home/circleci/project/builder/build.go:392 +0x812
github.com/tinygo-org/tinygo/builder.jobWorker(0xc000815020, 0xc000814fc0)
        /home/circleci/project/builder/jobs.go:165 +0xe0
created by github.com/tinygo-org/tinygo/builder.runJobs
        /home/circleci/project/builder/jobs.go:84 +0xc5
make: *** [Makefile:10: minimal1] Fehler 2
```
```
(go1.16.7) mustang:webrtc-tinygo-wasm jonas% make minimal2
tinygo build -opt 0 -o minimal/main.out ./minimal/main.go
/usr/bin/ld: /tmp/tinygo248647844/main.o: in function `(math/big.nat).shl':
/home/jonas/sdk/go1.16.7/src/math/big/nat.go:1011: undefined reference to `math/big.shlVU'
/usr/bin/ld: /tmp/tinygo248647844/main.o: in function `math/big.divisors':
/home/jonas/sdk/go1.16.7/src/math/big/natconv.go:497: undefined reference to `math/big.mulAddVWW'
/usr/bin/ld: /tmp/tinygo248647844/main.o: in function `(math/big.nat).divLarge':
/home/jonas/sdk/go1.16.7/src/math/big/nat.go:712: undefined reference to `math/big.shlVU'
/usr/bin/ld: /home/jonas/sdk/go1.16.7/src/math/big/nat.go:716: undefined reference to `math/big.shlVU'
/usr/bin/ld: /home/jonas/sdk/go1.16.7/src/math/big/nat.go:732: undefined reference to `math/big.shrVU'
/usr/bin/ld: /tmp/tinygo248647844/main.o: in function `(math/big.nat).divBasic':
/home/jonas/sdk/go1.16.7/src/math/big/nat.go:768: undefined reference to `math/big.mulWW'
/usr/bin/ld: /home/jonas/sdk/go1.16.7/src/math/big/nat.go:779: undefined reference to `math/big.mulWW'
/usr/bin/ld: /home/jonas/sdk/go1.16.7/src/math/big/nat.go:786: undefined reference to `math/big.mulAddVWW'
/usr/bin/ld: /home/jonas/sdk/go1.16.7/src/math/big/nat.go:791: undefined reference to `math/big.subVV'
/usr/bin/ld: /home/jonas/sdk/go1.16.7/src/math/big/nat.go:793: undefined reference to `math/big.addVV'
/usr/bin/ld: /tmp/tinygo248647844/main.o: in function `(math/big.nat).divRecursiveStep':
/home/jonas/sdk/go1.16.7/src/math/big/nat.go:912: undefined reference to `math/big.subVW'
/usr/bin/ld: /home/jonas/sdk/go1.16.7/src/math/big/nat.go:913: undefined reference to `math/big.subVV'
/usr/bin/ld: /home/jonas/sdk/go1.16.7/src/math/big/nat.go:915: undefined reference to `math/big.subVW'
/usr/bin/ld: /home/jonas/sdk/go1.16.7/src/math/big/nat.go:922: undefined reference to `math/big.subVV'
/usr/bin/ld: /home/jonas/sdk/go1.16.7/src/math/big/nat.go:924: undefined reference to `math/big.subVW'
/usr/bin/ld: /home/jonas/sdk/go1.16.7/src/math/big/nat.go:943: undefined reference to `math/big.subVW'
/usr/bin/ld: /home/jonas/sdk/go1.16.7/src/math/big/nat.go:944: undefined reference to `math/big.subVV'
/usr/bin/ld: /home/jonas/sdk/go1.16.7/src/math/big/nat.go:946: undefined reference to `math/big.subVW'
/usr/bin/ld: /home/jonas/sdk/go1.16.7/src/math/big/nat.go:954: undefined reference to `math/big.subVV'
/usr/bin/ld: /home/jonas/sdk/go1.16.7/src/math/big/nat.go:956: undefined reference to `math/big.subVW'
/usr/bin/ld: /tmp/tinygo248647844/main.o: in function `math/big.addAt':
/home/jonas/sdk/go1.16.7/src/math/big/nat.go:379: undefined reference to `math/big.addVV'
/usr/bin/ld: /home/jonas/sdk/go1.16.7/src/math/big/nat.go:382: undefined reference to `math/big.addVW'
/usr/bin/ld: /tmp/tinygo248647844/main.o: in function `math/big.basicMul':
/home/jonas/sdk/go1.16.7/src/math/big/nat.go:199: undefined reference to `math/big.addMulVVW'
/usr/bin/ld: /tmp/tinygo248647844/main.o: in function `(math/big.nat).mulAddWW':
/home/jonas/sdk/go1.16.7/src/math/big/nat.go:188: undefined reference to `math/big.mulAddVWW'
/usr/bin/ld: /tmp/tinygo248647844/main.o: in function `math/big.karatsuba':
/home/jonas/sdk/go1.16.7/src/math/big/nat.go:326: undefined reference to `math/big.subVV'
/usr/bin/ld: /home/jonas/sdk/go1.16.7/src/math/big/nat.go:328: undefined reference to `math/big.subVV'
/usr/bin/ld: /home/jonas/sdk/go1.16.7/src/math/big/nat.go:333: undefined reference to `math/big.subVV'
/usr/bin/ld: /home/jonas/sdk/go1.16.7/src/math/big/nat.go:335: undefined reference to `math/big.subVV'
/usr/bin/ld: /tmp/tinygo248647844/main.o: in function `math/big.karatsubaAdd':
/home/jonas/sdk/go1.16.7/src/math/big/nat.go:249: undefined reference to `math/big.addVV'
/usr/bin/ld: /home/jonas/sdk/go1.16.7/src/math/big/nat.go:250: undefined reference to `math/big.addVW'
/usr/bin/ld: /tmp/tinygo248647844/main.o: in function `math/big.karatsubaSub':
/home/jonas/sdk/go1.16.7/src/math/big/nat.go:256: undefined reference to `math/big.subVV'
/usr/bin/ld: /home/jonas/sdk/go1.16.7/src/math/big/nat.go:257: undefined reference to `math/big.subVW'
/usr/bin/ld: /tmp/tinygo248647844/main.o: in function `(math/big.nat).sub':
/home/jonas/sdk/go1.16.7/src/math/big/nat.go:142: undefined reference to `math/big.subVV'
/usr/bin/ld: /home/jonas/sdk/go1.16.7/src/math/big/nat.go:144: undefined reference to `math/big.subVW'
/usr/bin/ld: /tmp/tinygo248647844/main.o: in function `(math/big.nat).sqr':
/home/jonas/sdk/go1.16.7/src/math/big/nat.go:568: undefined reference to `math/big.mulWW'
/usr/bin/ld: /tmp/tinygo248647844/main.o: in function `math/big.basicSqr':
/home/jonas/sdk/go1.16.7/src/math/big/nat.go:504: undefined reference to `math/big.mulWW'
/usr/bin/ld: /home/jonas/sdk/go1.16.7/src/math/big/nat.go:508: undefined reference to `math/big.mulWW'
/usr/bin/ld: /home/jonas/sdk/go1.16.7/src/math/big/nat.go:510: undefined reference to `math/big.addMulVVW'
/usr/bin/ld: /home/jonas/sdk/go1.16.7/src/math/big/nat.go:512: undefined reference to `math/big.shlVU'
/usr/bin/ld: /home/jonas/sdk/go1.16.7/src/math/big/nat.go:513: undefined reference to `math/big.addVV'
/usr/bin/ld: /tmp/tinygo248647844/main.o: in function `math/big.karatsubaSqr':
/home/jonas/sdk/go1.16.7/src/math/big/nat.go:538: undefined reference to `math/big.subVV'
/usr/bin/ld: /home/jonas/sdk/go1.16.7/src/math/big/nat.go:539: undefined reference to `math/big.subVV'
/usr/bin/ld: /tmp/tinygo248647844/main.o: in function `(math/big.nat).montgomery':
/home/jonas/sdk/go1.16.7/src/math/big/nat.go:239: undefined reference to `math/big.subVV'
/usr/bin/ld: /home/jonas/sdk/go1.16.7/src/math/big/nat.go:226: undefined reference to `math/big.addMulVVW'
/usr/bin/ld: /home/jonas/sdk/go1.16.7/src/math/big/nat.go:228: undefined reference to `math/big.addMulVVW'
collect2: Fehler: ld gab 1 als Ende-Status zurück
error: failed to link /tmp/tinygo248647844/main: exit status 1
make: *** [Makefile:13: minimal2] Fehler 1
```
```
(go1.16.7) mustang:webrtc-tinygo-wasm jonas% make minimal3
tinygo build -opt z -o minimal/main.out ./minimal/main.go
```

The last one works just fine. I'm not sure what's going on here.

**Comment by aykevl** [comment]
How can I reproduce this error? I tried compiling the minimal package but it didn't work:

```
~/src/github.com/tinygo-org/tinygo/tmp/webrtc-tinygo-wasm/minimal$ tinygo build -o test.wasm -target=wasm
go: github.com/pion/randutil@v0.1.0 (replaced by ../../../../../git/vonas/randutil): reading /home/ayke/src/git/vonas/randutil/go.mod: open /home/ayke/src/git/vonas/randutil/go.mod: no such file or directory
```

**Comment by ungive** [comment]
The replace directive `../../../../../git/vonas/randutil` probably doesn't exist on your computer, which is why it failed. I accidentally kept it there. It's removed in the last commit. Let me know if there are any other issues.
