### ISSUE TITLE
SIGSEGV when compiling for wasm-target

### ISSUE THREAD

**Issue by abrander** [tinygo-org/tinygo#2253]
Using tinygo version 0.20.0 linux/amd64 (using go version go1.17.3 and LLVM version 11.0.0) installed from official deb package.

Minimal example resulting in a crash:

```go
package main

import (
	"syscall/js"
)

var _ = js.FuncOf(nil)

func main() {
}
```

The `nil`-argument to `js.FuncOf` is not important, the behavior is the same for a "real" argument.

Compiling the above minimal example using `tinygo build -o /dev/null -target wasm main.go` results in a SIGSEGV:

```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x7fa400000008 pc=0x39b7b17]

runtime stack:
runtime.throw({0x4498341, 0x7fa4884d1600})
	/usr/local/go/src/runtime/panic.go:1198 +0x71
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:719 +0x396

goroutine 26 [syscall]:
runtime.cgocall(0xd8e270, 0xc0006c1938)
	/usr/local/go/src/runtime/cgocall.go:156 +0x5c fp=0xc0006c1910 sp=0xc0006c18d8 pc=0xa6b2fc
tinygo.org/x/go-llvm._Cfunc_LLVMRunPassManager(0x7fa488328560, 0x7fa488002aa0)
	_cgo_gotypes.go:8888 +0x4c fp=0xc0006c1938 sp=0xc0006c1910 pc=0xc4d34c
tinygo.org/x/go-llvm.PassManager.Run.func1({0xc6bc79}, {0xc0006c1998})
	/go/pkg/mod/tinygo.org/x/go-llvm@v0.0.0-20210325115028-e7b85195e81c/ir.go:1998 +0x70 fp=0xc0006c1978 sp=0xc0006c1938 pc=0xc69f50
tinygo.org/x/go-llvm.PassManager.Run({0x7fa488328560}, {0x4494688})
	/go/pkg/mod/tinygo.org/x/go-llvm@v0.0.0-20210325115028-e7b85195e81c/ir.go:1998 +0x19 fp=0xc0006c1998 sp=0xc0006c1978 pc=0xc69e99
github.com/tinygo-org/tinygo/transform.Optimize({0xc000056dc8}, 0xc00017ca20, 0x2, 0x0, 0x5)
	/home/circleci/project/transform/optimizer.go:64 +0x28c fp=0xc0006c1d90 sp=0xc0006c1998 pc=0xd42d6c
github.com/tinygo-org/tinygo/builder.optimizeProgram({0x4435520}, 0xc00017ca20)
	/home/circleci/project/builder/build.go:740 +0x1ed fp=0xc0006c1df0 sp=0xc0006c1d90 pc=0xd566cd
github.com/tinygo-org/tinygo/builder.Build.func2(0x0)
	/home/circleci/project/builder/build.go:386 +0x657 fp=0xc0006c1f58 sp=0xc0006c1df0 pc=0xd556b7
github.com/tinygo-org/tinygo/builder.jobWorker(0x0, 0x0)
	/home/circleci/project/builder/jobs.go:182 +0xad fp=0xc0006c1fc0 sp=0xc0006c1f58 pc=0xd5e3ad
github.com/tinygo-org/tinygo/builder.runJobs·dwrap·14()
	/home/circleci/project/builder/jobs.go:101 +0x2a fp=0xc0006c1fe0 sp=0xc0006c1fc0 pc=0xd5e06a
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc0006c1fe8 sp=0xc0006c1fe0 pc=0xacafa1
created by github.com/tinygo-org/tinygo/builder.runJobs
	/home/circleci/project/builder/jobs.go:101 +0x1a5
	
...
```

I have tried to solve this - and given up, it's way too deep into LLVM-land. Any hints on how to solve this?

**Comment by dgryski** [comment]
This seems to have been fixed.
```
~/go/src/github.com/dgryski/bug $ cat bug.go
package main

import (
	"syscall/js"
)

var _ = js.FuncOf(nil)

func main() {
}
~/go/src/github.com/dgryski/bug $ tinygo build -o /dev/null -target wasm bug.go
~/go/src/github.com/dgryski/bug $
```
