### ISSUE TITLE
tinygo segfault building vanadium/go.lib/set on target=wasi

### ISSUE THREAD

**Issue by dgryski** [tinygo-org/tinygo#2408]
```
~/go/src/github.com/vanadium/go.lib/set $ tinygo test -target=wasi
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7a80bc4]

runtime stack:
runtime.throw({0x7db2ef8, 0x7fff6c2250c6})
	/Users/dgryski/go/src/go.googlesource.com/go/src/runtime/panic.go:1198 +0x71
runtime.sigpanic()
	/Users/dgryski/go/src/go.googlesource.com/go/src/runtime/signal_unix.go:719 +0x396

goroutine 47 [syscall]:
runtime.cgocall(0x43602b0, 0xc0008f6cd0)
	/Users/dgryski/go/src/go.googlesource.com/go/src/runtime/cgocall.go:156 +0x5c fp=0xc0008f6ca8 sp=0xc0008f6c70 pc=0x40087fc
tinygo.org/x/go-llvm._Cfunc_LLVMBuildCall(0x12f04820, 0x0, 0xc0005ffdb8, 0x3, 0x12f0a770)
	_cgo_gotypes.go:1677 +0x4d fp=0xc0008f6cd0 sp=0xc0008f6ca8 pc=0x4212f6d
tinygo.org/x/go-llvm.Builder.CreateCall.func2({0x12f0a770}, {0x0}, 0xc000100000, 0x5ffdb8, 0x0)
	/Users/dgryski/go/pkg/mod/tinygo.org/x/go-llvm@v0.0.0-20210907125547-fd2d62ea06be/ir.go:1840 +0xae fp=0xc0008f6d38 sp=0xc0008f6cd0 pc=0x423db4e
tinygo.org/x/go-llvm.Builder.CreateCall({0xc004d83f40}, {0x7da67e0}, {0xc0005ffdb8, 0x3, 0x210ecd936cd63}, {0x0, 0xc004c671e0})
	/Users/dgryski/go/pkg/mod/tinygo.org/x/go-llvm@v0.0.0-20210907125547-fd2d62ea06be/ir.go:1840 +0xa5 fp=0xc0008f6da0 sp=0xc0008f6d38 pc=0x423da05
github.com/tinygo-org/tinygo/compiler/llvmutil.EmitPointerPack({0x12f08ff0}, {0x13008960}, {0xc00029c030, 0xe}, 0x1, {0xc0030c32c8, 0x1, 0x1})
	/Users/dgryski/go/src/github.com/tinygo-org/tinygo/compiler/llvmutil/wordpack.go:105 +0x53c fp=0xc0008f6e98 sp=0xc0008f6da0 pc=0x429d57c
github.com/tinygo-org/tinygo/compiler.(*builder).emitPointerPack(...)
	/Users/dgryski/go/src/github.com/tinygo-org/tinygo/compiler/llvm.go:37
github.com/tinygo-org/tinygo/compiler.(*builder).createMakeInterface(0xc001a1e120, {0x9284d00}, {0x7e19250, 0x9284d00}, 0xd)
	/Users/dgryski/go/src/github.com/tinygo-org/tinygo/compiler/interface.go:25 +0x8e fp=0xc0008f6ef8 sp=0xc0008f6e98 pc=0x42c702e
github.com/tinygo-org/tinygo/compiler.(*builder).createMapLookup(0xc001a1e120, {0x7e19250, 0x9284d00}, {0x7e19390, 0xc003d5f620}, {0xc004c671e0}, {0x200000003}, 0x1, 0xc000032000)
	/Users/dgryski/go/src/github.com/tinygo-org/tinygo/compiler/map.go:89 +0x24b fp=0xc0008f7020 sp=0xc0008f6ef8 pc=0x42ce1cb
github.com/tinygo-org/tinygo/compiler.(*builder).createExpr(0xc001a1e120, {0x7e1fb00, 0xc000132460})
	/Users/dgryski/go/src/github.com/tinygo-org/tinygo/compiler/compiler.go:1723 +0xb58 fp=0xc0008f7278 sp=0xc0008f7020 pc=0x42b4cd8
github.com/tinygo-org/tinygo/compiler.(*builder).createInstruction(0xc001a1e120, {0x7e1fab8, 0xc000132460})
	/Users/dgryski/go/src/github.com/tinygo-org/tinygo/compiler/compiler.go:1077 +0x9ea fp=0xc0008f7438 sp=0xc0008f7278 pc=0x42b06ea
github.com/tinygo-org/tinygo/compiler.(*builder).createFunction(0xc001a1e120)
	/Users/dgryski/go/src/github.com/tinygo-org/tinygo/compiler/compiler.go:981 +0x18fc fp=0xc0008f7868 sp=0xc0008f7438 pc=0x42af6bc
github.com/tinygo-org/tinygo/compiler.(*compilerContext).createPackage(0xc004c1c3c0, {0xc004a44780}, 0xc004a6cde0)
	/Users/dgryski/go/src/github.com/tinygo-org/tinygo/compiler/compiler.go:759 +0x8ad fp=0xc0008f7ad0 sp=0xc0008f7868 pc=0x42adc0d
github.com/tinygo-org/tinygo/compiler.CompilePackage({0xc00029c030, 0xe}, 0xc0002e5340, 0xc004a6cde0, {0x12008200}, 0xc00016e0b0, 0x0)
	/Users/dgryski/go/src/github.com/tinygo-org/tinygo/compiler/compiler.go:278 +0x2ca fp=0xc0008f7bd0 sp=0xc0008f7ad0 pc=0x42a98ca
github.com/tinygo-org/tinygo/builder.Build.func1(0x0)
	/Users/dgryski/go/src/github.com/tinygo-org/tinygo/builder/build.go:244 +0x11b fp=0xc0008f7f58 sp=0xc0008f7bd0 pc=0x431c19b
github.com/tinygo-org/tinygo/builder.jobWorker(0x0, 0x0)
	/Users/dgryski/go/src/github.com/tinygo-org/tinygo/builder/jobs.go:191 +0xad fp=0xc0008f7fc0 sp=0xc0008f7f58 pc=0x4324d8d
github.com/tinygo-org/tinygo/builder.runJobs·dwrap·13()
	/Users/dgryski/go/src/github.com/tinygo-org/tinygo/builder/jobs.go:110 +0x2a fp=0xc0008f7fe0 sp=0xc0008f7fc0 pc=0x4324a4a
runtime.goexit()
	/Users/dgryski/go/src/go.googlesource.com/go/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc0008f7fe8 sp=0xc0008f7fe0 pc=0x40689e1
created by github.com/tinygo-org/tinygo/builder.runJobs
	/Users/dgryski/go/src/github.com/tinygo-org/tinygo/builder/jobs.go:110 +0x229

```

Builds and passes fine on native

```
~/go/src/github.com/vanadium/go.lib/set $ tinygo test
ok  	v.io/x/lib/set	0.153s
```

**Comment by inkeliz** [comment]
I'm having similar issue with `-target wasm`. But, there's two bugs:

- If `-gc "conservative"` or default: It crashes (similar to error reported)
- If `-gc` is not `conservative`: It will build forever (until run out of memory).

------------

```
goroutine 14 [syscall]:
runtime.cgocall(0x76e840, 0xc009314d70)
        C:/hostedtoolcache/windows/go/1.17.3/x64/src/runtime/cgocall.go:156 +0x4a fp=0xc009314d48 sp=0xc009314d10 pc=0x40448a
tinygo.org/x/go-llvm._Cfunc_LLVMBuildCall(0x854ad40, 0x0, 0xc0102b5f68, 0x3, 0x8502250)
        _cgo_gotypes.go:1709 +0x5b fp=0xc009314d70 sp=0xc009314d48 pc=0x62cfbb
tinygo.org/x/go-llvm.Builder.CreateCall.func2({0x8502250}, {0x0}, 0xc000880000, 0x102b5f68, 0x0)
        C:/Users/runneradmin/go/pkg/mod/tinygo.org/x/go-llvm@v0.0.0-20210325115028-e7b85195e81c/ir.go:1840 +0xae fp=0xc009314dd8 sp=0xc009314d70 pc=0x65bdae
tinygo.org/x/go-llvm.Builder.CreateCall({0xc001b93700}, {0x41dffcc}, {0xc0102b5f68, 0x3, 0xc009314ea8}, {0x0, 0xc0089e2be0})
        C:/Users/runneradmin/go/pkg/mod/tinygo.org/x/go-llvm@v0.0.0-20210325115028-e7b85195e81c/ir.go:1840 +0xa5 fp=0xc009314e40 sp=0xc009314dd8 pc=0x65bc65
github.com/tinygo-org/tinygo/compiler/llvmutil.EmitPointerPack({0xc009314f70}, {0x64a37f}, {0xc00014cb20, 0x1a}, 0x1, {0xc00d2d8af0, 0x1, 0x1})
        D:/a/tinygo/tinygo/compiler/llvmutil/wordpack.go:105 +0x53c fp=0xc009314f38 sp=0xc009314e40 pc=0x6b5e1c
github.com/tinygo-org/tinygo/compiler.(*builder).emitPointerPack(...)
        D:/a/tinygo/tinygo/compiler/llvm.go:37
github.com/tinygo-org/tinygo/compiler.(*builder).createMakeInterface(0xc011f51c20, {0x4264b08}, {0x425e530, 0xc00d751c00}, 0x0)
        D:/a/tinygo/tinygo/compiler/interface.go:25 +0x8e fp=0xc009314f98 sp=0xc009314f38 pc=0x6e030e
github.com/tinygo-org/tinygo/compiler.(*builder).createExpr(0xc011f51c20, {0x4265330, 0xc008fd9810})
        D:/a/tinygo/tinygo/compiler/compiler.go:1733 +0x1aa5 fp=0xc009315230 sp=0xc009314f98 pc=0x6ceb25
github.com/tinygo-org/tinygo/compiler.(*builder).createInstruction(0xc011f51c20, {0x42652e8, 0xc008fd9810})
        D:/a/tinygo/tinygo/compiler/compiler.go:1077 +0x9ea fp=0xc0093153f0 sp=0xc009315230 pc=0x6c95ea
github.com/tinygo-org/tinygo/compiler.(*builder).createFunction(0xc011f51c20)
        D:/a/tinygo/tinygo/compiler/compiler.go:981 +0x18fc fp=0xc009315820 sp=0xc0093153f0 pc=0x6c85bc
github.com/tinygo-org/tinygo/compiler.(*compilerContext).createPackage(0xc008ea0300, {0xc007365cc0}, 0xc0106fe420)
        D:/a/tinygo/tinygo/compiler/compiler.go:726 +0x62f fp=0xc009315a88 sp=0xc009315820 pc=0x6c688f
github.com/tinygo-org/tinygo/compiler.CompilePackage({0xc00014cb20, 0xc008a90720}, 0xc00017a000, 0xc0106fe420, {0x0}, 0x0, 0x0)
        D:/a/tinygo/tinygo/compiler/compiler.go:278 +0x2ca fp=0xc009315b88 sp=0xc009315a88 pc=0x6c280a
github.com/tinygo-org/tinygo/builder.Build.func1(0x0)
        D:/a/tinygo/tinygo/builder/build.go:244 +0x11b fp=0xc009315f58 sp=0xc009315b88 pc=0x734ebb
github.com/tinygo-org/tinygo/builder.jobWorker(0x0, 0x0)
        D:/a/tinygo/tinygo/builder/jobs.go:191 +0xad fp=0xc009315fc0 sp=0xc009315f58 pc=0x73db6d
github.com/tinygo-org/tinygo/builder.runJobs·dwrap·14()
        D:/a/tinygo/tinygo/builder/jobs.go:110 +0x2a fp=0xc009315fe0 sp=0xc009315fc0 pc=0x73d82a
runtime.goexit()
        C:/hostedtoolcache/windows/go/1.17.3/x64/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc009315fe8 sp=0xc009315fe0 pc=0x466241
created by github.com/tinygo-org/tinygo/builder.runJobs
        D:/a/tinygo/tinygo/builder/jobs.go:110 +0x229

goroutine 1 [chan receive]:
github.com/tinygo-org/tinygo/builder.runJobs(0x4178940, 0xc005bbe250)
        D:/a/tinygo/tinygo/builder/jobs.go:142 +0x314
github.com/tinygo-org/tinygo/builder.Build({0x411d370, 0x1}, {0xc00001a180, 0x41d4c81}, 0xc000209c50, 0xc01367f688)
        D:/a/tinygo/tinygo/builder/build.go:743 +0x2d85
main.Build({0x411d370, 0x1}, {0xc00001a180, 0x9}, 0x41d4c71)
        D:/a/tinygo/tinygo/main.go:150 +0x8f
main.main()
        D:/a/tinygo/tinygo/main.go:1261 +0x32cd
```

**Comment by dgryski** [comment]
This package builds and tests fine now on native and wasi.
