### ISSUE TITLE
compiler: ICE on template.ParseFS() during init()

### ISSUE THREAD

**Issue by ii64** [tinygo-org/tinygo#2886]
Commit: https://github.com/tinygo-org/tinygo/commit/97842b367c0fc92499f73b9b63014247906f9190

<details>
<summary>env</summary>

```tinygo version 0.24.0-dev linux/amd64 (using go version go1.18.2 and LLVM version 13.0.1)```
```
> tinygo env
GOOS="linux"
GOARCH="amd64"
GOROOT="/opt/go"
GOPATH="/home/ii64/go"
GOCACHE="/home/ii64/.cache/tinygo"
CGO_ENABLED="1"
TINYGOROOT="/mnt/z/Workdir/tinygo"
```
</details>

<details>
<summary>trace</summary>

Command: `tinygo build -no-debug -gc leaking -opt z -target wasm main.go`
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x7123a8]

goroutine 59 [running]:
github.com/tinygo-org/tinygo/interp.(*runner).run(0xc004352000, 0xc0044a7090, {0xc007294d10, 0x3, 0x0?}, 0xc0019218f0, {0xc000826ba0, 0x28})
	/mnt/z/Workdir/tinygo/interp/interpreter.go:351 +0x53a8
github.com/tinygo-org/tinygo/interp.(*runner).run(0xc004352000, 0xc0053fe3c0, {0xc007275f10, 0x4, 0x0?}, 0xc001919b00, {0xc000826930, 0x24})
	/mnt/z/Workdir/tinygo/interp/interpreter.go:520 +0x8194
github.com/tinygo-org/tinygo/interp.(*runner).run(0xc004352000, 0xc0054698b0, {0xc007275d90, 0x5, 0x0?}, 0xc001919890, {0xc006f7bcc0, 0x20})
	/mnt/z/Workdir/tinygo/interp/interpreter.go:520 +0x8194
github.com/tinygo-org/tinygo/interp.(*runner).run(0xc004352000, 0xc005468690, {0xc007274990, 0x5, 0x0?}, 0xc0017c63f0, {0xc006f7bc40, 0x1c})
	/mnt/z/Workdir/tinygo/interp/interpreter.go:520 +0x8194
github.com/tinygo-org/tinygo/interp.(*runner).run(0xc004352000, 0xc001ecbdb0, {0xc00215cd50, 0x3, 0x0?}, 0xc001765b60, {0xc004c3f050, 0x18})
	/mnt/z/Workdir/tinygo/interp/interpreter.go:520 +0x8194
github.com/tinygo-org/tinygo/interp.(*runner).run(0xc004352000, 0xc001eca280, {0xc006ec7410, 0x7, 0x0?}, 0xc0016e3d40, {0xc004c3eee8, 0x14})
	/mnt/z/Workdir/tinygo/interp/interpreter.go:520 +0x8194
github.com/tinygo-org/tinygo/interp.(*runner).run(0xc004352000, 0xc001e9ce60, {0xc006ec6a10, 0x7, 0x0?}, 0xc0016bf260, {0xc006efa2e0, 0x10})
	/mnt/z/Workdir/tinygo/interp/interpreter.go:520 +0x8194
github.com/tinygo-org/tinygo/interp.(*runner).run(0xc004352000, 0xc001e9cb40, {0xc006d4a610, 0x6, 0x0?}, 0xc001d5c720, {0xc006ee9980, 0xc})
	/mnt/z/Workdir/tinygo/interp/interpreter.go:520 +0x8194
github.com/tinygo-org/tinygo/interp.(*runner).run(0xc004352000, 0xc0044a7ef0, {0xc006d3a6d0, 0x1, 0x0?}, 0xc001e6fe60, {0xc006d56338, 0x8})
	/mnt/z/Workdir/tinygo/interp/interpreter.go:520 +0x8194
github.com/tinygo-org/tinygo/interp.(*runner).run(0xc004352000, 0xc0044a7ea0, {0x0, 0x0, 0xc000eec3d8?}, 0x0, {0x80fcce, 0x4})
	/mnt/z/Workdir/tinygo/interp/interpreter.go:520 +0x8194
github.com/tinygo-org/tinygo/interp.Run({0xc00006ddf0?}, 0x3f?)
	/mnt/z/Workdir/tinygo/interp/interp.go:115 +0x6cc
github.com/tinygo-org/tinygo/builder.optimizeProgram({0x7f20706e3d78?}, 0xc000242900)
	/mnt/z/Workdir/tinygo/builder/build.go:1065 +0x33
github.com/tinygo-org/tinygo/builder.Build.func5(0xc003e492c0)
	/mnt/z/Workdir/tinygo/builder/build.go:561 +0x5ed
github.com/tinygo-org/tinygo/builder.runJob(0xc003e49320, 0x0?)
	/mnt/z/Workdir/tinygo/builder/jobs.go:222 +0x4f
created by github.com/tinygo-org/tinygo/builder.runJobs
	/mnt/z/Workdir/tinygo/builder/jobs.go:123 +0x5db
```
</details>

[report.zip](https://github.com/tinygo-org/tinygo/files/8811216/report.zip)

Thanks.

**Comment by ii64** [comment]
Moving `tpl = template.Must(template.ParseFS(efs, "**/*.html"))` to `runtime.main` solved the issue

**Comment by jakebailey** [comment]
I checked, and this was fixed a while back. #3020 was a dupe of this, and so this was fixed by #3164
