### ISSUE TITLE
optimizeProgram: panic: comparing values of different size

### ISSUE THREAD

**Issue by eliasnaur** [tinygo-org/tinygo#4106]
Given this program,

```go
package main

import (
	"fmt"
)

func init() {
	fmt.Println("a")
}

func main() {
}
```

crashes during flashing with

```
$ tinygo flash -target stm32f4disco main.go
panic: comparing values of different size

goroutine 168 [running]:
github.com/tinygo-org/tinygo/interp.rawValue.equal(...)
	/Users/a/proj/tinygo/interp/memory.go:776
github.com/tinygo-org/tinygo/interp.(*runner).interpretICmp(0x100626bc0?, {0x10069c670, 0x1400bf86960}, {0x10069c618, 0x1400b474eb0}, 0x20)
	/Users/a/proj/tinygo/interp/interpreter.go:882 +0x328
github.com/tinygo-org/tinygo/interp.(*runner).run(0x1400dfbf540, 0x140096e0e10, {0x1400bf75410, 0x5, 0x100649a40?}, 0x14003f4cd80, {0x1400927fb30, 0x18})
	/Users/a/proj/tinygo/interp/interpreter.go:698 +0x2144
github.com/tinygo-org/tinygo/interp.(*runner).run(0x1400dfbf540, 0x140096e0dc0, {0x1400bf75210, 0x6, 0x1400bf86720?}, 0x14003f4cc60, {0x1400927fa58, 0x14})
	/Users/a/proj/tinygo/interp/interpreter.go:526 +0x646c
github.com/tinygo-org/tinygo/interp.(*runner).run(0x1400dfbf540, 0x140096e0cd0, {0x1400bcfec10, 0x6, 0x1400bcc22a0?}, 0x14003f037d0, {0x1400bfa6700, 0x10})
	/Users/a/proj/tinygo/interp/interpreter.go:526 +0x646c
github.com/tinygo-org/tinygo/interp.(*runner).run(0x1400dfbf540, 0x140096e01e0, {0x1400bcc8010, 0x6, 0x100649a40?}, 0x14003f030e0, {0x1400bccb1e0, 0xc})
	/Users/a/proj/tinygo/interp/interpreter.go:526 +0x646c
github.com/tinygo-org/tinygo/interp.(*runner).run(0x1400dfbf540, 0x140096e0190, {0x1400bc45e90, 0x4, 0x100649a40?}, 0x14003f02cf0, {0x1400bcc18c8, 0x8})
	/Users/a/proj/tinygo/interp/interpreter.go:526 +0x646c
github.com/tinygo-org/tinygo/interp.(*runner).run(0x1400dfbf540, 0x140096e0140, {0x0, 0x0, 0x1400420f8b8?}, 0x0, {0x100549693, 0x4})
	/Users/a/proj/tinygo/interp/interpreter.go:526 +0x646c
github.com/tinygo-org/tinygo/interp.Run({0x1400420fde8?}, 0x1004dabb8?, 0xa0?)
	/Users/a/proj/tinygo/interp/interp.go:117 +0x4e8
github.com/tinygo-org/tinygo/builder.optimizeProgram({0x113705300?}, 0x140001d6b80, 0x7?)
	/Users/a/proj/tinygo/builder/build.go:1033 +0x3c
github.com/tinygo-org/tinygo/builder.Build.func5(0x14007186300)
	/Users/a/proj/tinygo/builder/build.go:576 +0x4c0
github.com/tinygo-org/tinygo/builder.runJob(0x14007186420, 0x0?)
	/Users/a/proj/tinygo/builder/jobs.go:222 +0x48
created by github.com/tinygo-org/tinygo/builder.runJobs in goroutine 1
	/Users/a/proj/tinygo/builder/jobs.go:123 +0x434
```

I'm using tinygo built from `70f1a5429af40138c775e7e923abcc1da6807f99`.

**Comment by deadprogram** [comment]
This is no longer happening with the latest TinyGo versions, so now closing. Please reopen if needed. Thanks @eliasnaur
